theme: minima
title: Welcome to my Github Page!
author: Michael Iacono
email: iaconom821@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First time for everything. Going to put in the hard work and attention that's required to make this task possible. Switching things up takes effort, patience, and persistence. Those are going to be the values that get me where I need to go.

# social links
twitter_username: iaconom821 # DO NOT include the @ character, or else the build will fail!
github_username:  iaconom821 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
